### PR TITLE
Update actions for v3's

### PR DESCRIPTION
**Pull request by jbrown-xentity**
Related to https://github.com/GSA/data.gov/issues/4005

See latest versions of [download-artifact](https://github.com/actions/download-artifact/tags) and [actions/checkout](https://github.com/actions/checkout/tags)

### CODE REVIEW

**Comment by btylerburton** [comment]
I think there's still a few to cover. From this list: https://github.com/GSA/catalog.data.gov/actions/runs/3228383267

```
- actions/checkout
- actions/upload-artifact
- actions/download-artifact
- docker/login-action
- docker/build-push-action
```

**Comment by jbrown-xentity** [comment]
All 5 uses should now be covered

**Comment by jbrown-xentity** [comment]
No more warnings at least... https://github.com/GSA/catalog.data.gov/actions/runs/3250731443

**Review by nickumia-reisys — APPROVED** [review]
🆙

**Pull request merged**
