### PR TITLE
pinning setuptools to working version per github issue: https://githu…

### PR DESCRIPTION
**Pull request by btylerburton**
…b.com/cloudfoundry/python-buildpack/issues/574

### CODE REVIEW

**Comment by btylerburton** [comment]
This passed in dev. https://github.com/GSA/catalog.data.gov/actions/runs/2921671027

**Comment by btylerburton** [comment]
Also, not sure if we have a ticket for this or if I should make on for posterity. Feedback appreciated.

**Comment by nickumia-reisys** [comment]
This might not be needed anymore if the problem was fixed [here](https://github.com/cloudfoundry/python-buildpack/issues/574#issuecomment-1226605056)?  The latest python buildpak should have a version of setuptools that will work out of the box now.

**Comment by nickumia-reisys** [comment]
This ("sort of") happened before (a few times). Here's another example: https://github.com/GSA/catalog.data.gov/pull/388

**Comment by nickumia-reisys** [comment]
Also, we don't have a ticket and it might be good to have one.  I'll just put this here (even though it's tangentially related)... it seems like our Issues and PRs are the basis for our documentation which could work (but is definitely unorthodox).  If you're suggesting creating a ticket as a documentation step that would follow our history; but should the primary documentation for this be in an issue?  I don't think so.

**Comment by btylerburton** [comment]
I'm going to revert the psycopg-binary changes and run a build in dev to see if it passes.

I'd like to hear more about your thoughts on how to document this stuff. I've seen it done as a captain's log in a wiki, but that wasn't searchable enough and only really worked for smaller periods of activity.

**Pull request merged**
