### PR TITLE
removes fix for python buildpak missing proper version of setuptools

### PR DESCRIPTION
**Pull request by btylerburton**
Related to:
- https://gsa-tts.slack.com/archives/C2N85536E/p1661952790965969

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
### Still using the old broken version:

image

Link: https://github.com/GSA/catalog.data.gov/runs/8119042954?check_suite_focus=true#step:5:165

**Comment by nickumia-reisys** [comment]
It really doesn't like you @btylerburton 😭

**Comment by btylerburton** [comment]
Boo! And that was after following up with cg-support with a working fix.

**Review by nickumia-reisys — APPROVED** [review]
🗝️

**Comment by btylerburton** [comment]
did you try running this with the default python_buildpak?

**Comment by nickumia-reisys** [comment]
Oh.. no I didn't @btylerburton 😅 New PR time!

**Comment by nickumia-reisys** [comment]
Completes:
- https://github.com/GSA/catalog.data.gov/pull/532

**Pull request merged**
