### PR TITLE
Update ckan.ini

### PR DESCRIPTION
**Pull request by jbrown-xentity**
Add necessary config items from ckan2.10 changelog: https://docs.ckan.org/en/2.10/changelog.html#migration-notes-2-10

Related to https://github.com/GSA/data.gov/issues/2138

### CODE REVIEW

**Comment by btylerburton** [comment]
Do you think we need this signing key, too?

```beaker.session.validate_key = CHANGE_ME```

**Comment by btylerburton** [comment]
Same failing test. I'm not sure if anyone has tried running this locally to repro the results.

**Comment by rshewitt** [comment]
> Same failing test. I'm not sure if anyone has tried running this locally to repro the results.

i'll look further into this

**Comment by rshewitt** [comment]
for some reason cypress isn't able to find the feedback modal where `class=fba-modal-dialog`. @btylerburton do you see an issue with the new element being selected? I'm concerned about, what looks like, a generated id appended to the end of the touchpoint class name ( i.e. #touchpoints-form-`fd986495` ) and whether this is a viable name to use

**Comment by rshewitt** [comment]
omg `#` vs `.` . i'm not paying attention.

**Comment by btylerburton** [comment]
I think `fd986495` is touchpoints id for our form so it probably wouldn't change. That said, we can look for the modal by class instead of id and the test will be a little less brittle.

**Comment by jbrown-xentity** [comment]
@GSA/data-gov-dev-team if someone could approve this, we could get this rolled out asap... And thanks for the test fixes @btylerburton and @rshewitt !

**Review by btylerburton — APPROVED** [review]

**Pull request merged**
