### PR TITLE
Fix .snyk ignores

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to
- https://github.com/GSA/data.gov/issues/3416

Changes:
- Ignore `ckan` vulnerability
- Fix `.snyk` formatting
- Move `.snyk` to `ckan/.snyk` since the project is in `ckan/`

References:
- https://docs.snyk.io/snyk-cli/test-for-vulnerabilities/the-.snyk-file

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
I verified in https://github.com/GSA/catalog.data.gov/actions/runs/3650304384/jobs/6166115760 that this will do what we want it to 🦺

**Comment by FuhuXia** [comment]
Why is that GH job operation cancelled?

**Comment by nickumia-reisys** [comment]
I cancelled it because I didn't want it to make the PR since it would have made the PR to `ignore-ckan-snyk` instead of `main` and we want the PR to `main` @FuhuXia

**Comment by nickumia-reisys** [comment]
### The important part is that there's one vulnerability to fix:
image

### And that's the only one it will change in the file:
image


@FuhuXia

**Review by robert-bryson — APPROVED** [review]

**Pull request merged**
