### PR TITLE
New settings for datagovtheme

### PR DESCRIPTION
**Pull request by avdata99**
Add config values to fix template errors at DataGovTheme (PR in DataGovTheme to use these settings approved [here](https://github.com/GSA/ckanext-datagovtheme/pull/43/files))

Full details [here](https://github.com/GSA/catalog.data.gov/issues/50)

Tested locally
Screenshot-20200601120625-959x652

### CODE REVIEW

**Comment by woodt** [comment]
One more step here ... add `ckan/requirements.txt` ... but otherwise, this makes me very happy :-)

**Comment by avdata99** [comment]
Reopen since we changed the approach here, now we continue using master for `DataGovTheme`

**Comment by avdata99** [comment]
> One more step here ... add `ckan/requirements.txt` ... but otherwise, this makes me very happy :-)

Updated PR @woodt. Added reqs and dependencies updated.

**Comment by avdata99** [comment]
> I think this is OK. I'm assuming the new config settings are required? If so, make sure to update the ini file in the ansible world to add them (see the README). I can (gladly) help with this if you have questions!

Ok, I will check the README at new catalog repo and let you know if I have some doubts

**Pull request merged**
