### PR TITLE
[Snyk + GH Actions] Update requirements

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Update requirements
- Updated `requirements.in` + `requirements.txt`
- Auto-generated by [snyk.yml][1]

[1]: https://github.com/gsa/catalog.data.gov/.github/workflows/snyk.yml

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
This is technically a bad PR, the `update-requirements` failed:
```bash
  Running setup.py develop for ckanext-qa
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [6 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/srv/app/src/ckanext-qa/setup.py", line 2, in <module>
            from ckanext.qa import __version__
        ModuleNotFoundError: No module named 'ckanext.qa'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/srv/app/src/ckanext-qa/setup.py", line 2, in <module>
        from ckanext.qa import __version__
    ModuleNotFoundError: No module named 'ckanext.qa'
    [end of output]
```

Not sure why, but it might fix itself tomorrow?  Otherwise we can fix it manually.

**Comment by btylerburton** [comment]
Is this good to go? I don't see the error in the actions.

**Comment by nickumia-reisys** [comment]
This is the link to the error: https://github.com/GSA/catalog.data.gov/actions/runs/4564162251/jobs/8053578477#step:4:2839

We should probably link to the snyk scan in the issue, but the error is in the `update-requirements` command, not in the `make test`

**Comment by nickumia-reisys** [comment]
This PR won't have any effect on production as is.

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/catalog.data.gov/pull/906

**Pull request closed without merging**
