### PR TITLE
more locales to filter out

### PR DESCRIPTION
**Pull request by FuhuXia**
CKAN 2.10.0 [added](https://github.com/ckan/ckan/commit/5bc0bcc692ee02b1766af39ee8a8dba6b8139896) locales `bs` and `no`.

We received tons of requests to `/no/*`, 2 millions in a month, peaked at 10 per second.

image

### CODE REVIEW

**Review by jbrown-xentity — APPROVED** [review]
Good catch @FuhuXia

**Comment by jbrown-xentity** [comment]
Bummer @FuhuXia , looks like there's an unrelated problem with building the efs tools used in the docker image... Looks like this will have to be addressed, as the SOLR docker image won't work until we get this fixed? https://github.com/GSA/catalog.data.gov/blob/main/solr/Dockerfile#L13-L18

**Comment by FuhuXia** [comment]
efs-utils v2.0.0 was released 3 days ago. Need to update install steps.

**Review by jbrown-xentity — APPROVED** [review]
Thanks @FuhuXia

**Pull request merged**
